# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_info', models.CharField(max_length=1000)),
            ],
        ),
    ]
