# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=2)),
                ('age', models.IntegerField()),
                ('years_experience', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
